### ISSUE TITLE
BlueZ & Raspberry Pi

### ISSUE THREAD

**Issue by robotastic** [sandeepmistry/node-ancs#4]
I have node-ancs working fine on my MacBook, but I can't get it working on my Raspberry Pi. I have a CSR dongle. I have tried the latest version of Raspbian Wheezy and built BlueZ 5.21 and installed it. I also tried Raspbian Jessie which has Bluez 5.21 built in packages.

With the Pi I get ANCS messages from test.js: discovered / connected / services and characteristics
I get the pairing message on the iPhone and in settings->bluetooth, it will show that it is connected for a while.
However the connection drops and ANCS never prints out recent notifications. 

Does anyone have a good step-by-step guide on how to get node-ANCS up and running on a Raspberry Pi? I have bluetoothd running and I think I have everything installed correctly, but what hciconfig & hcitool commands do you issue before turning on ANCS? I have tried hciconfig reset a bunch. I went through Issue #2  and tried everything in there.I have also tried BlueZ 5.16. Has anyone gotten this working with a recent version of BlueZ?

Any help would be awesome. I have spent 2 days trying all sorts of combinations.

**Comment by sandeepmistry** [comment]
It's been a while, but this change to noble should fix things on the pairing side: https://github.com/sandeepmistry/noble/commit/20e9af815cc5f55c340352489666b31ced540f92

iOS 8.1.3 seems to stay connected for longer as well.

I've also updated the package.json to use the latest rev of noble.

**Comment by byteblox** [comment]
I have been working with noble for research and it works really well - thank you for all the work on this.
Sorry its been a while since your last post on this issue.  What i am seeing is similar situation.  I have a Pi-2 using noble (raspian - latest noble as of today) and an iOS device 8.1.2 acting as peripheral.
Project working fine except for disconnects every 30secs or so (on iOS receiving the didUnSubscribe event).  looking at the iOS device log i see

`Jun 25 16:06:48 .... BTServer[56] <Error>: ATT        Failed to locate GAP primary service on device "C842C7B0-0A3E-5A80-6C50-1F6822619C75" `
after which i immediately get ..
`Jun 25 16:06:48  .... [714] <Warning>: peripheral: Peripheral didUnsubscribeFromCharacteristic... 1`

i am currently restarting the scan but its a bit messy.   Any ideas why the iOS would report that message and then disconnect?

any thoughts would be really helpful

info

Linux raspberrypi 3.18.7-v7+ #755 SMP PREEMPT Thu Feb 12 17:20:48 GMT 2015 armv7l GNU/Linux

bluez 5-31

iOS 8.1.2 (will be checking 8.3 later today)

**Comment by sandeepmistry** [comment]
@byteblox nice digging!

noble doesn't currently support responding to requests that the peripheral sends. Not sure if this is why the iOS device is disconnecting. You could attempt to patch noble and see if this makes a difference..
